In [31]:
import pandas as pd

In [32]:
data={
    "name":['Bhavya','Aman','Pawan'],
    "emp_id":[100,200,300],
    "unit":[10,20,30],
    "City":['gurugram','raipur','banaras'],
    "Cp":[100,200,300],
    "Sp":[200,100,400],
    "Diff": [100,100,100],
    "Total_cost": [100,100,300]


}

df=pd.DataFrame(data)
df

     name  emp_id  unit      City   Cp   Sp  Diff  Total_cost
0  Bhavya     100    10  gurugram  100  200   100         100
1    Aman     200    20    raipur  200  100   100         100
2   Pawan     300    30   banaras  300  400   100         300

In [33]:
df["Prof_loss"]=df["Diff"].apply(lambda x: "Profit" if x>0 else "Loss")
df

     name  emp_id  unit      City   Cp   Sp  Diff  Total_cost Prof_loss
0  Bhavya     100    10  gurugram  100  200   100         100    Profit
1    Aman     200    20    raipur  200  100   100         100    Profit
2   Pawan     300    30   banaras  300  400   100         300    Profit

In [ ]:
df["order_type"] = df["unit"].apply(
    lambda x: "Bulk Order" if x > 20 else "Normal Order"
)
df

SyntaxError: invalid syntax (2517986748.py, line 4)